# Generated by Django 4.2.7 on 2024-12-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('centro', '0007_alter_cursos_options'),
        ('convivencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amonestaciones',
            unique_together={('IdAlumno', 'Fecha', 'Hora', 'Profesor', 'Tipo', 'Comentario', 'DerivadoConvivencia', 'FamiliarComunicado', 'FechaComunicado', 'HoraComunicado', 'Medio', 'TelefonoComunicado', 'ObservacionComunicado', 'curso_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='sanciones',
            unique_together={('IdAlumno', 'Fecha', 'Fecha_fin', 'Sancion', 'Comentario', 'curso_academico')},
        ),
        migrations.CreateModel(
            name='PropuestasSancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateField(blank=True, null=True)),
                ('salida', models.DateField()),
                ('motivo_salida', models.TextField(blank=True, null=True)),
                ('ignorar', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.alumnos')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
                ('ultima_amonestacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='convivencia.amonestaciones')),
            ],
            options={
                'verbose_name': 'Propuesta de alumnado sancionable',
                'verbose_name_plural': 'Propuestas de alumnado sancionable',
            },
        ),
    ]
