# Generated by Django 4.2.7 on 2024-12-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0002_alter_amonestaciones_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestassancion',
            name='entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='propuestassancion',
            name='salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
