# Generated by Django 4.2.7 on 2024-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0003_alter_propuestassancion_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestassancion',
            name='graves',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propuestassancion',
            name='leves',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propuestassancion',
            name='peso',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
