# Generated by Django 4.2.7 on 2025-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0006_alter_amonestaciones_idalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amonestaciones',
            name='Medio',
            field=models.CharField(blank=True, choices=[('1', 'Teléfono'), ('2', 'PASEN')], max_length=1, null=True),
        ),
    ]
