# Generated by Django 4.2.7 on 2025-07-21 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0029_preferenciahorario_curso_academico'),
        ('convivencia', '0007_alter_amonestaciones_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amonestaciones',
            name='DerivadoConvivencia',
            field=models.BooleanField(default=False, verbose_name='Derivado a Aula Horizonte'),
        ),
        migrations.AlterField(
            model_name='amonestaciones',
            name='Medio',
            field=models.CharField(blank=True, choices=[('1', 'Teléfono'), ('2', 'PASEN (Observaciones compartidas)')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='IntervencionAulaHorizonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tramo_horario', models.CharField(max_length=10)),
                ('tarea_asignada', models.TextField(help_text='Descripción de la tarea que debía realizar el alumno/a.')),
                ('tarea_realizada', models.TextField(blank=True, help_text='Trabajo realizado efectivamente durante la intervención.')),
                ('motivo', models.TextField(help_text='Motivo de la derivación. Conducta observada.')),
                ('reflexion_alumno', models.TextField(blank=True, help_text='Reflexión escrita o verbal del alumno/a (si la hubo).')),
                ('necesita_reubicacion', models.BooleanField(default=False, help_text='¿Fue necesario ubicar al alumno/a en otro grupo?')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aula_horizonte', to='centro.alumnos')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones_creadas', to='centro.profesores')),
                ('grupo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino_aula_horizonte', to='centro.cursos')),
                ('profesor_atiende', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atiende_aula_horizonte', to='centro.profesores')),
                ('profesor_envia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envia_aula_horizonte', to='centro.profesores')),
            ],
            options={
                'verbose_name': 'Registro del Aula Horizonte',
                'verbose_name_plural': 'Registros del Aula Horizonte',
                'ordering': ['-fecha', 'tramo_horario'],
            },
        ),
    ]
