# Generated by Django 4.2.7 on 2025-07-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0029_preferenciahorario_curso_academico'),
        ('convivencia', '0008_alter_amonestaciones_derivadoconvivencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencionaulahorizonte',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
        migrations.AlterField(
            model_name='intervencionaulahorizonte',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='intervencionaulahorizonte',
            name='tramo_horario',
            field=models.CharField(choices=[('1', 'Primera (1ª)'), ('2', 'Segunda (2ª)'), ('3', 'Tercera (3ª)'), ('4', 'Recreo (REC)'), ('5', 'Cuarta (4ª)'), ('6', 'Quinta (5ª)'), ('7', 'Sexta (6ª)')], max_length=1),
        ),
    ]
