# Generated by Django 4.2.7 on 2024-10-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0002_cursos_cursohorarios_profesores_nombrehorarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarea', models.CharField(blank=True, max_length=255, null=True)),
                ('Materia', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha', models.DateField()),
                ('Tramo', models.IntegerField(choices=[(1, '1ª Hora'), (2, '2ª Hora'), (3, '3ª Hora'), (4, 'RECREO'), (5, '4ª Hora'), (6, '5ª Hora'), (7, '6ª Hora')])),
                ('Aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_aula', to='centro.aulas')),
                ('ProfesorAusente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_ausente', to='centro.profesores')),
                ('ProfesorConfirma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_confirma', to='centro.profesores')),
                ('ProfesorNotifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_notifica', to='centro.profesores')),
                ('ProfesoresGuardia', models.ManyToManyField(blank=True, related_name='guardias_profesoradoguardia', to='centro.profesores', verbose_name='Profesorado Guardia')),
                ('Unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursos')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
            ],
            options={
                'verbose_name': 'Item Guardia',
                'verbose_name_plural': 'Items Guardia',
            },
        ),
        migrations.CreateModel(
            name='TiempoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('tramo', models.IntegerField(choices=[(1, 'Tramos 1h'), (2, 'Tramos 2h'), (3, 'Tramos 3h'), (4, 'Tramos 4h'), (5, 'Tramos 5h'), (6, 'Tramos 6h'), (7, 'Tramos 7h')])),
                ('tiempo_asignado', models.IntegerField()),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
                ('item_guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_guardia', to='guardias.itemguardia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.profesores')),
            ],
        ),
    ]
