# Generated by Django 4.2.7 on 2024-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='CursoHorarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesores',
            name='NombreHorarios',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
