# Generated by Django 4.2.7 on 2024-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0002_cursos_cursohorarios_profesores_nombrehorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='Dificultad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
