# Generated by Django 4.2.7 on 2024-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0004_aulas_aulahorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='NEAE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='PDC',
            field=models.BooleanField(default=False),
        ),
    ]
