# Generated by Django 4.2.7 on 2024-10-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0005_alumnos_neae_alumnos_pdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='SustitutoDe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustitutos', to='centro.profesores', verbose_name='Sustituto de'),
        ),
    ]
