# Generated by Django 4.2.7 on 2024-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0006_profesores_sustitutode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
