# Generated by Django 4.2.7 on 2024-12-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0007_alter_cursos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposMaterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=80)),
                ('Nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.niveles')),
            ],
            options={
                'verbose_name': 'Grupo de Materias',
                'verbose_name_plural': 'Grupos de Materias',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materia', models.CharField(max_length=80)),
                ('Abreviatura', models.CharField(max_length=10)),
                ('InicioVigencia', models.PositiveSmallIntegerField()),
                ('FinalVigencia', models.PositiveSmallIntegerField()),
                ('CuentaSesionEvaluacion', models.BooleanField(default=True)),
                ('HorasSemanales', models.PositiveSmallIntegerField(default=0)),
                ('GrupoMateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.gruposmaterias')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='MatriculasAlumnado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Repetidor', models.BooleanField(default=False)),
                ('Alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.alumnos')),
                ('Unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursos')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
            ],
            options={
                'verbose_name': 'Matrícula Alumnado',
                'verbose_name_plural': 'Matrículas Alumnado',
            },
        ),
        migrations.CreateModel(
            name='MateriasAlumnado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.materias')),
                ('Matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.matriculasalumnado')),
                ('Profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.profesores')),
            ],
        ),
    ]
