# Generated by Django 4.2.7 on 2024-12-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0008_gruposmaterias_materias_matriculasalumnado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='Nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.niveles'),
        ),
    ]
