# Generated by Django 4.2.7 on 2024-12-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0009_materias_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='FinalVigencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
