# Generated by Django 4.2.7 on 2024-12-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analres', '0002_alter_calificaciones_materia'),
        ('centro', '0010_alter_materias_finalvigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculasalumnado',
            name='Materias',
            field=models.ManyToManyField(to='centro.materias'),
        ),
        migrations.DeleteModel(
            name='MateriasAlumnado',
        ),
    ]
