# Generated by Django 4.2.7 on 2024-12-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analres', '0003_alter_calificaciones_unique_together_and_more'),
        ('centro', '0011_matriculasalumnado_materias_delete_materiasalumnado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='GrupoMateria',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='Nivel',
        ),
        migrations.RemoveField(
            model_name='matriculasalumnado',
            name='Alumno',
        ),
        migrations.RemoveField(
            model_name='matriculasalumnado',
            name='Materias',
        ),
        migrations.RemoveField(
            model_name='matriculasalumnado',
            name='Unidad',
        ),
        migrations.RemoveField(
            model_name='matriculasalumnado',
            name='curso_academico',
        ),
        migrations.DeleteModel(
            name='GruposMaterias',
        ),
        migrations.DeleteModel(
            name='Materias',
        ),
        migrations.DeleteModel(
            name='MatriculasAlumnado',
        ),
    ]
