# Generated by Django 4.2.7 on 2025-01-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0014_centros_infoalumnos_centroorigen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centros',
            unique_together={('Codigo', 'Nombre')},
        ),
    ]
