# Generated by Django 4.2.7 on 2025-01-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0016_infoalumnos_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles',
            name='NombresAntiguos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
