# Generated by Django 4.2.7 on 2025-01-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0017_niveles_nombresantiguos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoalumnos',
            name='Alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_adicional', to='centro.alumnos'),
        ),
    ]
