# Generated by Django 4.2.7 on 2025-05-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0018_alter_infoalumnos_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('abr', models.CharField(blank=True, max_length=20)),
                ('nombre_horarios', models.CharField(blank=True, max_length=100)),
                ('horas', models.PositiveSmallIntegerField(default=0)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.niveles')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nivel__Abr', 'abr'],
            },
        ),
        migrations.CreateModel(
            name='MateriaImpartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.cursos')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.profesores')),
            ],
            options={
                'verbose_name': 'Materia impartida',
                'verbose_name_plural': 'Materias impartidas',
                'ordering': ['curso__Nivel__Abr', 'curso__Curso', 'materia__abr'],
                'unique_together': {('profesor', 'materia', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='MatriculaMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.alumnos')),
                ('materia_impartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.materiaimpartida')),
            ],
            options={
                'verbose_name': 'Matrícula de materia',
                'verbose_name_plural': 'Matrículas de materias',
                'unique_together': {('alumno', 'materia_impartida')},
            },
        ),
    ]
