# Generated by Django 4.2.7 on 2025-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0019_materia_materiaimpartida_matriculamateria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
