# Generated by Django 4.2.7 on 2025-05-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0020_alter_materia_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN/EAN')),
                ('editorial', models.CharField(blank=True, max_length=200)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('anyo_implantacion', models.PositiveIntegerField(blank=True, null=True)),
                ('importe_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('es_digital', models.BooleanField(default=False)),
                ('incluir_en_cheque_libro', models.BooleanField(default=False)),
                ('es_otro_material', models.BooleanField(default=False)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='centro.materia')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_texto', to='centro.niveles')),
            ],
        ),
    ]
