# Generated by Django 4.2.7 on 2025-05-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0021_librotexto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MomentoRevisionLibros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RevisionLibroAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_libros', to='centro.alumnos')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.estadolibro')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.librotexto')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.materia')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.momentorevisionlibros')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_libros', to='centro.profesores')),
            ],
            options={
                'unique_together': {('alumno', 'libro', 'momento')},
            },
        ),
    ]
