# Generated by Django 4.2.7 on 2025-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0022_estadolibro_momentorevisionlibros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentorevisionlibros',
            name='estados',
            field=models.ManyToManyField(related_name='momentos', to='centro.estadolibro'),
        ),
    ]
