# Generated by Django 4.2.7 on 2025-05-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0023_momentorevisionlibros_estados'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revisionlibroalumno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='revisionlibroalumno',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='revisionlibroalumno',
            unique_together={('profesor', 'alumno', 'libro', 'momento', 'curso_academico')},
        ),
    ]
