# Generated by Django 4.2.7 on 2025-05-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0024_alter_revisionlibroalumno_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionlibroalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.alumnos'),
        ),
        migrations.CreateModel(
            name='RevisionLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.librotexto')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.materia')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.momentorevisionlibros')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.profesores')),
            ],
            options={
                'unique_together': {('profesor', 'materia', 'libro', 'momento', 'fecha', 'curso_academico')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='revisionlibroalumno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='revisionlibroalumno',
            name='revision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='centro.revisionlibro'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='revisionlibroalumno',
            unique_together={('revision', 'alumno')},
        ),
        migrations.RemoveField(
            model_name='revisionlibroalumno',
            name='curso_academico',
        ),
        migrations.RemoveField(
            model_name='revisionlibroalumno',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='revisionlibroalumno',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='revisionlibroalumno',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='revisionlibroalumno',
            name='momento',
        ),
        migrations.RemoveField(
            model_name='revisionlibroalumno',
            name='profesor',
        ),
    ]
