# Generated by Django 4.2.7 on 2025-05-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0025_alter_revisionlibroalumno_alumno_revisionlibro_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revisionlibro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='revisionlibro',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centro.cursos'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='revisionlibro',
            unique_together={('profesor', 'curso', 'materia', 'libro', 'momento', 'fecha', 'curso_academico')},
        ),
    ]
