# Generated by Django 4.2.7 on 2025-07-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0026_alter_revisionlibro_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librotexto',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
        migrations.AddField(
            model_name='materia',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
        migrations.AddField(
            model_name='materiaimpartida',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
        migrations.AddField(
            model_name='matriculamateria',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
    ]
