# Generated by Django 4.2.7 on 2025-07-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0027_librotexto_curso_academico_materia_curso_academico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.JSONField(default=dict)),
                ('flexibilidad_inicio', models.BooleanField(default=False)),
                ('flexibilidad_fin', models.BooleanField(default=False)),
                ('guardias', models.JSONField(default=list)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_horaria', to='centro.profesores')),
            ],
        ),
    ]
