# Generated by Django 4.2.7 on 2025-07-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0028_preferenciahorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciahorario',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
    ]
