# Generated by Django 4.2.7 on 2025-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0029_preferenciahorario_curso_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='EquipoEducativo',
            field=models.ManyToManyField(blank=True, related_name='cursos_equipo_educativo', to='centro.profesores', verbose_name='Equipo Educativo'),
        ),
    ]
