# Generated by Django 4.2.7 on 2025-09-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0030_alter_cursos_equipoeducativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
