# Generated by Django 4.2.7 on 2025-09-05 11:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0031_cursos_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelManagers(
            name='cursos',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='EquipoEducativo',
        ),
    ]
