# Generated by Django 4.2.7 on 2025-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0032_alter_cursos_options_alter_cursos_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['Orden', 'id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='Orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
