# Generated by Django 4.2.7 on 2025-11-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0033_alter_cursos_options_cursos_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='Centro_EP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnado_ESO', to='centro.centros'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='Centro_ESO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnado_BTOCF', to='centro.centros'),
        ),
        migrations.AddField(
            model_name='centros',
            name='Compensatoria',
            field=models.BooleanField(default=False),
        ),
    ]
