# Generated by Django 4.2.7 on 2026-02-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0034_alumnos_centro_ep_alumnos_centro_eso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendariosLectivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_academico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='centro.cursoacademico')),
            ],
            options={
                'verbose_name': 'Calendario Lectivo',
                'verbose_name_plural': 'Calendarios Lectivos',
            },
        ),
        migrations.CreateModel(
            name='PeriodosLectivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('dias_lectivos', models.IntegerField(default=0, editable=False)),
                ('calendario_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_lectivos', to='centro.calendarioslectivos')),
            ],
            options={
                'verbose_name': 'Periodo Lectivo',
                'verbose_name_plural': 'Periodos Lectivos',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Festivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festivos', to='centro.periodoslectivos')),
            ],
            options={
                'verbose_name': 'Día Festivo',
                'verbose_name_plural': 'Días Festivos',
                'unique_together': {('periodo_lectivo', 'fecha')},
            },
        ),
    ]
