# Generated by Django 4.2.7 on 2026-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0035_calendarioslectivos_periodoslectivos_festivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioslectivos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='festivos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='periodoslectivos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
    ]
