# Generated by Django 4.2.7 on 2026-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0036_calendarioslectivos_descripcion_festivos_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarioslectivos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='Direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='DniTutor1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI Tutor 1'),
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='DniTutor2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI Tutor 2'),
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='Localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='NombreTutor1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Tutor 1'),
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='NombreTutor2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Tutor 2'),
        ),
        migrations.AddField(
            model_name='infoalumnos',
            name='Telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
