# Generated by Django 4.2.7 on 2024-12-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0008_gruposmaterias_materias_matriculasalumnado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Convocatoria', models.CharField(choices=[('EVI', 'Evaluación inicial'), ('1EV', '1ª Evaluación'), ('2EV', '2ª Evaluacion'), ('3EV', '3ª Evaluacion'), ('FFP', 'Final FP'), ('Ord', 'Ordinaria'), ('Ext', 'Extraordinaria')], default='1EV', max_length=3)),
                ('Calificacion', models.PositiveSmallIntegerField()),
                ('Presentado', models.BooleanField(default=True)),
                ('Materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.materiasalumnado')),
                ('Matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.matriculasalumnado')),
            ],
            options={
                'verbose_name': 'Calificaciones',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('Matricula', 'Convocatoria', 'Materia')},
            },
        ),
    ]
