# Generated by Django 4.2.7 on 2024-12-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0011_matriculasalumnado_materias_delete_materiasalumnado'),
        ('analres', '0002_alter_calificaciones_materia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.alumnos'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='Calificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='Materia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('Alumno', 'Convocatoria', 'Materia')},
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='Matricula',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='Presentado',
        ),
    ]
