# Generated by Django 4.2.7 on 2024-12-29 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0012_remove_materias_grupomateria_remove_materias_nivel_and_more'),
        ('analres', '0003_alter_calificaciones_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='Nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NivelCalificaciones', to='centro.niveles'),
        ),
    ]
