# Generated by Django 4.2.7 on 2025-01-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0013_infoalumnos'),
        ('analres', '0004_calificaciones_nivel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('Alumno', 'Convocatoria', 'Materia', 'curso_academico')},
        ),
    ]
