# Generated by Django 4.2.7 on 2025-01-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0017_niveles_nombresantiguos'),
        ('analres', '0005_alter_calificaciones_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresAlumnado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Convocatoria', models.CharField(choices=[('EVI', 'Evaluación inicial'), ('1EV', '1ª Evaluación'), ('2EV', '2ª Evaluacion'), ('3EV', '3ª Evaluacion'), ('FFP', 'Final FP'), ('Ord', 'Ordinaria'), ('Ext', 'Extraordinaria')], default='1EV', max_length=3)),
                ('EstimacionPromocion', models.BooleanField(blank=True, default=None, null=True)),
                ('EficaciaTransito', models.BooleanField(blank=True, default=None, null=True)),
                ('EvaluacionPositivaTodo', models.BooleanField(blank=True, default=None, null=True)),
                ('EficaciaRepeticion', models.BooleanField(blank=True, default=None, null=True)),
                ('IdoneidadCursoEdad', models.BooleanField(blank=True, default=None, null=True)),
                ('AbandonoEscolar', models.BooleanField(blank=True, default=None, null=True)),
                ('Alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.alumnos')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
            ],
        ),
    ]
