# Generated by Django 4.2.7 on 2025-01-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0018_alter_infoalumnos_alumno'),
        ('analres', '0006_indicadoresalumnado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadoresalumnado',
            options={'verbose_name': 'Indicadores del Alumnado', 'verbose_name_plural': 'Indicadores del Alumnado'},
        ),
        migrations.AddField(
            model_name='indicadoresalumnado',
            name='Modalidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='indicadoresalumnado',
            unique_together={('curso_academico', 'Alumno', 'Convocatoria')},
        ),
    ]
