# Generated by Django 4.2.7 on 2025-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analres', '0008_alter_indicadoresalumnado_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresalumnado',
            name='Promocion',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
