# Generated by Django 4.2.7 on 2024-08-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=200)),
                ('prioridad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciasTic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.aulas')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
                ('elementos', models.ManyToManyField(to='tde.elemento')),
                ('prioridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tde.prioridad')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.profesores')),
            ],
            options={
                'verbose_name': 'Incidencia TIC',
                'verbose_name_plural': 'Incidencias TIC',
            },
        ),
    ]
