# Generated by Django 4.2.7 on 2024-09-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposActuaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoActuacion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tipo Actuación',
                'verbose_name_plural': 'Tipos de Actuación',
            },
        ),
        migrations.CreateModel(
            name='ProtocoloAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('abierto', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='centro.alumnos')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='centro.profesores')),
            ],
            options={
                'verbose_name': 'Protocolo Absentismo',
                'verbose_name_plural': 'Protocolos Absentismo',
            },
        ),
        migrations.CreateModel(
            name='Actuaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Comentario', models.TextField(blank=True)),
                ('Notificada', models.BooleanField(default=False)),
                ('Medio', models.CharField(blank=True, choices=[('1', 'Teléfono'), ('2', 'PASEN'), ('3', 'Correo ordinario'), ('4', 'Correo certificado'), ('5', 'Otros')], max_length=1, null=True)),
                ('Telefono', models.TextField(blank=True, null=True)),
                ('Protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='absentismo.protocoloabs')),
                ('Tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tipo_de', to='absentismo.tiposactuaciones')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
            ],
            options={
                'verbose_name': 'Actuación',
                'verbose_name_plural': 'Actuaciones',
            },
        ),
    ]
