# Generated by Django 4.2.7 on 2024-11-08 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absentismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaltasProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('DiaCompletoJustificada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('DiaCompletoNoJustificada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('TramosJustificados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('TramosNoJustificados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('NotificacionDiaCompleto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('NotificacionTramos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='absentismo.protocoloabs')),
            ],
            options={
                'verbose_name': 'Faltas de un protocolo',
                'verbose_name_plural': 'Faltas de los protocolos',
            },
        ),
    ]
