# Generated by Django 4.2.7 on 2026-02-25 22:19

import absentismo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absentismo', '0003_alter_faltasprotocolo_options_informessc_informefm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoInformeSSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to=absentismo.models._ruta_adjunto_ssc, verbose_name='Archivo PDF')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='absentismo.informessc', verbose_name='Informe SSC')),
            ],
            options={
                'verbose_name': 'Adjunto informe SSC',
                'verbose_name_plural': 'Adjuntos informe SSC',
                'ordering': ['orden', 'subido_en'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoInformeFM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to=absentismo.models._ruta_adjunto_fm, verbose_name='Archivo PDF')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='absentismo.informefm', verbose_name='Informe FM')),
            ],
            options={
                'verbose_name': 'Adjunto informe FM',
                'verbose_name_plural': 'Adjuntos informe FM',
                'ordering': ['orden', 'subido_en'],
            },
        ),
    ]
