# Generated by Django 4.2.7 on 2026-01-27 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0034_alumnos_centro_ep_alumnos_centro_eso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del Proceso')),
                ('centros_origen', models.ManyToManyField(blank=True, related_name='configuraciones_transito', to='centro.centros')),
                ('materias_implicadas', models.ManyToManyField(blank=True, to='centro.materia')),
            ],
            options={
                'verbose_name': 'Configuración de Tránsito',
                'verbose_name_plural': 'Configuraciones de Tránsito',
            },
        ),
        migrations.CreateModel(
            name='CampanaTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transito.configuraciontransito', verbose_name='Tipo de Tránsito')),
                ('curso_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.cursoacademico')),
            ],
            options={
                'verbose_name': 'Campaña de Tránsito',
                'verbose_name_plural': 'Campañas de Tránsito',
                'unique_together': {('curso_academico', 'configuracion')},
            },
        ),
        migrations.CreateModel(
            name='InformeDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestiones_generales', models.TextField(blank=True, null=True, verbose_name='Cuestiones Generales')),
                ('fortalezas', models.TextField(blank=True, null=True, verbose_name='Fortalezas Detectadas')),
                ('debilidades', models.TextField(blank=True, null=True, verbose_name='Debilidades Detectadas')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Departamento')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='transito.campanatransito')),
                ('centro_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_recibidos', to='centro.centros')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.materia')),
            ],
            options={
                'verbose_name': 'Informe de Departamento',
                'verbose_name_plural': 'Informes de Departamento',
                'unique_together': {('campana', 'materia', 'centro_origen')},
            },
        ),
    ]
