# Generated by Django 4.2.7 on 2026-01-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0034_alumnos_centro_ep_alumnos_centro_eso_and_more'),
        ('transito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMateriaDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_departamento', to='transito.campanatransito')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.departamentos')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.materia')),
            ],
            options={
                'verbose_name': 'Asignación Materia-Departamento',
                'verbose_name_plural': 'Asignaciones Materias-Departamentos',
                'unique_together': {('campana', 'materia')},
            },
        ),
    ]
