# Generated by Django 4.2.7 on 2026-01-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transito', '0003_campanatransito_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanatransito',
            name='nivel',
        ),
    ]
