# Generated by Django 4.2.7 on 2026-01-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0034_alumnos_centro_ep_alumnos_centro_eso_and_more'),
        ('transito', '0004_remove_campanatransito_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanatransito',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.niveles', verbose_name='Nivel Objetivo'),
        ),
    ]
