# Generated by Django 4.2.7 on 2026-01-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0034_alumnos_centro_ep_alumnos_centro_eso_and_more'),
        ('transito', '0005_campanatransito_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanatransito',
            name='nivel',
        ),
        migrations.AddField(
            model_name='campanatransito',
            name='niveles',
            field=models.ManyToManyField(blank=True, to='centro.niveles', verbose_name='Niveles Objetivo'),
        ),
    ]
