# Generated by Django 4.2.7 on 2026-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0034_alumnos_centro_ep_alumnos_centro_eso_and_more'),
        ('transito', '0006_remove_campanatransito_nivel_campanatransito_niveles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanatransito',
            name='niveles',
        ),
        migrations.AddField(
            model_name='configuraciontransito',
            name='niveles',
            field=models.ManyToManyField(blank=True, to='centro.niveles', verbose_name='Niveles Objetivo'),
        ),
    ]
