# Generated by Django 4.2.7 on 2026-01-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0034_alumnos_centro_ep_alumnos_centro_eso_and_more'),
        ('transito', '0007_remove_campanatransito_niveles_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campanatransito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='informedepartamento',
            name='autor',
        ),
        migrations.AddField(
            model_name='campanatransito',
            name='centros_origen',
            field=models.ManyToManyField(blank=True, related_name='configuraciones_transito', to='centro.centros'),
        ),
        migrations.AddField(
            model_name='campanatransito',
            name='descripcion',
            field=models.CharField(default='', max_length=200, verbose_name='Descripción del Proceso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campanatransito',
            name='materias_implicadas',
            field=models.ManyToManyField(blank=True, to='centro.materia'),
        ),
        migrations.AddField(
            model_name='campanatransito',
            name='niveles',
            field=models.ManyToManyField(blank=True, to='centro.niveles', verbose_name='Niveles Objetivo'),
        ),
        migrations.RemoveField(
            model_name='campanatransito',
            name='configuracion',
        ),
        migrations.DeleteModel(
            name='ConfiguracionTransito',
        ),
    ]
