# Generated by Django 4.2.7 on 2026-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transito', '0008_alter_campanatransito_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanatransito',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
