# Generated by Django 4.2.7 on 2024-09-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Reservable',
                'verbose_name_plural': 'Reservables',
            },
        ),
        migrations.CreateModel(
            name='TiposReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoReserva', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tipo Reserva',
                'verbose_name_plural': 'Tipos de Reservas',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.CharField(choices=[('1', 'Primera (1ª)'), ('2', 'Segunda (2ª)'), ('3', 'Tercera (3ª)'), ('4', 'Recreo (REC)'), ('5', 'Cuarta (4ª)'), ('6', 'Quinta (5ª)'), ('7', 'Sexta (6ª)')], default='1', max_length=1)),
                ('Profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.profesores')),
                ('Reservable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservable', to='reservas.reservables')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AddField(
            model_name='reservables',
            name='TiposReserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tipo_de', to='reservas.tiposreserva'),
        ),
    ]
