# Generated by Django 4.2.7 on 2025-01-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0018_alter_infoalumnos_alumno'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservas',
            unique_together={('Profesor', 'Fecha', 'Hora', 'Reservable', 'curso_academico')},
        ),
    ]
