# Generated by Django 4.2.7 on 2024-09-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0002_cursos_cursohorarios_profesores_nombrehorarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo', models.IntegerField(choices=[(1, 'Tramo 1'), (2, 'Tramo 2'), (3, 'Tramo 3'), (4, 'Tramo 4'), (5, 'Tramo 5'), (6, 'Tramo 6'), (7, 'Tramo 7')])),
                ('dia', models.IntegerField(choices=[(1, 'Día 1'), (2, 'Día 2'), (3, 'Día 3'), (4, 'Día 4'), (5, 'Día 5')])),
                ('materia', models.CharField(blank=True, max_length=255, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.aulas')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.profesores')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.cursos')),
            ],
            options={
                'verbose_name': 'Item de Horario',
                'verbose_name_plural': 'Items de Horario',
                'unique_together': {('tramo', 'dia', 'profesor', 'unidad', 'aula')},
            },
        ),
    ]
