# Generated by Django 4.2.7 on 2024-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhorario',
            name='dia',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='itemhorario',
            name='tramo',
            field=models.IntegerField(choices=[(1, '1ª Hora'), (2, '2ª Hora'), (3, '3ª Hora'), (4, 'RECREO'), (5, '4ª Hora'), (6, '5ª Hora'), (7, '6ª Hora')]),
        ),
    ]
