# Generated by Django 4.2.7 on 2025-01-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0018_alter_infoalumnos_alumno'),
        ('horarios', '0002_alter_itemhorario_dia_alter_itemhorario_tramo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemhorario',
            unique_together={('tramo', 'dia', 'profesor', 'unidad', 'aula', 'materia')},
        ),
    ]
