# Generated by Django 4.2.7 on 2025-09-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0030_alter_cursos_equipoeducativo'),
        ('horarios', '0003_alter_itemhorario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemhorario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemhorario',
            name='curso_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='itemhorario',
            unique_together={('tramo', 'dia', 'profesor', 'unidad', 'aula', 'materia', 'curso_academico')},
        ),
    ]
