# Generated by Django 4.2.7 on 2024-11-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0006_profesores_sustitutode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('FechaInicio', models.DateField()),
                ('Duracion', models.PositiveSmallIntegerField()),
                ('MedidaDuracion', models.CharField(choices=[('Dias', 'Días'), ('Horas', 'Horas')], default='Horas', max_length=10)),
                ('CosteAlumnado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DietasProfesorado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada')], default='Pendiente', max_length=10)),
                ('Alumnado', models.ManyToManyField(to='centro.alumnos')),
                ('Profesorado', models.ManyToManyField(related_name='actividades_participadas', to='centro.profesores')),
                ('Responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_organizadas', to='centro.profesores')),
                ('UnidadesAfectadas', models.ManyToManyField(to='centro.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AprobadoPor', models.CharField(choices=[('Consejo Escolar', 'Consejo Escolar'), ('Comisión Permanente', 'Comision Permanente')], max_length=50)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='DACE.actividades')),
            ],
        ),
    ]
