# Generated by Django 4.2.7 on 2025-07-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0027_librotexto_curso_academico_materia_curso_academico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_pagado', models.BooleanField(default=False)),
                ('compe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('HoraSalida', models.TimeField(blank=True, null=True)),
                ('HoraLlegada', models.TimeField(blank=True, null=True)),
                ('CosteAlumnado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('AportacionCentro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada')], default='Pendiente', max_length=10)),
                ('Alumnado', models.ManyToManyField(related_name='actividades_participadas', through='DACE.ActividadAlumno', to='centro.alumnos')),
                ('Profesorado', models.ManyToManyField(related_name='actividades_participadas', to='centro.profesores')),
                ('Responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_organizadas', to='centro.profesores')),
                ('UnidadesAfectadas', models.ManyToManyField(to='centro.cursos')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.cursoacademico')),
            ],
            options={
                'verbose_name': 'Actividad DACE',
                'verbose_name_plural': 'Actividades DACE',
                'unique_together': {('Titulo', 'Descripcion', 'Responsable', 'FechaInicio', 'FechaFin', 'HoraSalida', 'HoraLlegada')},
            },
        ),
        migrations.CreateModel(
            name='GastosActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('General', 'General'), ('Por alumno', 'Por alumno')], default='General', max_length=20)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='DACE.actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AprobadoPor', models.CharField(choices=[('Consejo Escolar', 'Consejo Escolar'), ('Comisión Permanente', 'Comision Permanente')], max_length=50)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='DACE.actividades')),
            ],
        ),
        migrations.AddField(
            model_name='actividadalumno',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_alumno', to='DACE.actividades'),
        ),
        migrations.AddField(
            model_name='actividadalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='centro.alumnos'),
        ),
        migrations.AlterUniqueTogether(
            name='actividadalumno',
            unique_together={('actividad', 'alumno')},
        ),
    ]
