# Generated by Django 4.2.7 on 2025-07-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DACE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de actividad',
                'verbose_name_plural': 'Estados de actividad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='actividades',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='DACE.estadoactividad'),
        ),
    ]
