# Generated by Django 4.2.7 on 2025-09-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DACE', '0002_estadoactividad_alter_actividades_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='EnProgramacion',
            field=models.BooleanField(default=False),
        ),
    ]
