# Generated by Django 4.2.7 on 2026-01-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0033_alter_cursos_options_cursos_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsuntoPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.cursoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asuntos_propios', to='centro.profesores')),
            ],
            options={
                'unique_together': {('profesor', 'fecha', 'curso_academico')},
            },
        ),
    ]
